language: cpp
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update -qq
  - sudo apt-get install -qq `cat DEPENDENCIES`
script:
  - mkdir -p test/build
  - pushd test/build
  - cmake ..
  - ctest --output-on-failure
  - popd
