language: cpp
env:
  - CMAKE_GENERATOR="Unix Makefiles"
  - CMAKE_GENERATOR="Ninja"
before_install:
  - git submodule update --init --recursive
  - sudo apt-add-repository -y ppa:kalakris/cmake
  - sudo apt-add-repository -y ppa:saiarcot895/chromium-dev
  - sudo apt-get update -qq
  - sudo apt-get install -qq `cat DEPENDENCIES`
  # Workaround to get Ninja to display verbose output
  - if [[ $CMAKE_GENERATOR == "Ninja" ]] ; then
     echo -e '!#/bin/bash\n/usr/bin/ninja -v $@' > ninja;
     chmod +x ninja;
     export PATH=`pwd`:${PATH};
    fi
script:
  - mkdir -p test/build
  - pushd test/build
  - which ninja
  - cmake .. -G "${CMAKE_GENERATOR}"
  - ctest --output-on-failure
  - popd
